default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: mercari2_development

test:
  <<: *default
  database: mercari2_test

production:
  <<: *default
  database: mercari2_production
  username: root
  password: mercari
  socket: /var/lib/mysql/mysql.sock
  host: localhost
